version: '3'

services:
  benefit_bistro:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/entrypoint.sh
    env_file:
      - ../.env
    ports:
      - "8000:8000"
