version: '3'

services:
  benefit_bistro:
    container_name: benefit_bistro
    image: benefit_bistro
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/entrypoint.sh
    env_file:
      - ../.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
      - redis
      - celery
    volumes:
      - ../alembic/versions:/app/alembic/versions

  database:
    container_name: database
    hostname: postgresql
    image: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../database_data:/var/lib/postgresql/data
      - ../database_backups:/backups
      - ../scripts/postgres:/scripts
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ../redis/data:/root/redis
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ 'redis-server', '--requirepass', '${REDIS_PASSWORD}' ]
    env_file:
      - ../.env

  celery:
    image: celery
    container_name: celery
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
      - celery_beat
    env_file:
      - ../.env
    command: [ './scripts/celery.sh', 'celery' ]

  celery_beat:
    image: celery_beat
    container_name: celery_beat
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    env_file:
      - ../.env
    command: [ './scripts/celery.sh', 'beat' ]

  flower:
    image: flower
    container_name: flower
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
      - celery
      - celery_beat
    env_file:
      - ../.env
    command: [ './scripts/celery.sh', 'flower' ]
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}


#networks:
#  default:
#    external: true
#    name: benefit_bistro_network
