name: main-workflow
run-name: ${{ github.actor }} is testing changes
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install requirements
        run: pip install -r ./requirements/prod.txt
      - name: Run flake8
        run: flake8 ./src -v
  type-cheks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
      - name: Install requirements
        run: pip install -r ./requirements/prod.txt
      - name: Run mypy
        run: mypy ./src
